services:
  - type: web
    name: api-merenda-facial
    env: python
    rootDir: backend
    buildCommand: pip install -r requirements.txt && python download_model.py
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    plan: free
    envVars:
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_SERVICE_ROLE_KEY
        sync: false
      - key: DATABASE_URL
        sync: false
      # Variável que diz ao InsightFace para baixar os modelos no diretório local do app na nuvem
      - key: INSIGHTFACE_HOME
        value: ./models
      - key: PYTHON_VERSION
        value: 3.11.9
